"""max gpa field to regulation

Revision ID: 015dc356727a
Revises: f81d66816c0d
Create Date: 2024-02-28 13:32:26.097117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015dc356727a'
down_revision: Union[str, None] = 'f81d66816c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulations', sa.Column('max_gpa', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulations', 'max_gpa')
    # ### end Alembic commands ###
