"""user divisions

Revision ID: 3e52d7ad73bb
Revises: 81edf5d3c514
Create Date: 2024-03-06 19:06:37.697471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e52d7ad73bb'
down_revision: Union[str, None] = '81edf5d3c514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_divisions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'division_id')
    )
    op.create_index(op.f('ix_user_divisions_division_id'), 'user_divisions', ['division_id'], unique=False)
    op.create_index(op.f('ix_user_divisions_user_id'), 'user_divisions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_divisions_user_id'), table_name='user_divisions')
    op.drop_index(op.f('ix_user_divisions_division_id'), table_name='user_divisions')
    op.drop_table('user_divisions')
    # ### end Alembic commands ###
