"""correct course id field

Revision ID: a8a90a9c5f5e
Revises: c37fee959d86
Create Date: 2024-03-10 22:07:02.116698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a90a9c5f5e'
down_revision: Union[str, None] = 'c37fee959d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_divisions', 'course_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_divisions', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
