"""course divisions

Revision ID: c37fee959d86
Revises: 3e52d7ad73bb
Create Date: 2024-03-06 19:07:31.408012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37fee959d86'
down_revision: Union[str, None] = '3e52d7ad73bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_divisions',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'division_id')
    )
    op.create_index(op.f('ix_course_divisions_course_id'), 'course_divisions', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_divisions_division_id'), 'course_divisions', ['division_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_divisions_division_id'), table_name='course_divisions')
    op.drop_index(op.f('ix_course_divisions_course_id'), table_name='course_divisions')
    op.drop_table('course_divisions')
    # ### end Alembic commands ###
