"""division model and relationships

Revision ID: c710a1a7b922
Revises: 5ebf2af933a8
Create Date: 2024-02-29 08:30:31.222342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c710a1a7b922'
down_revision: Union[str, None] = '5ebf2af933a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('group', sa.Boolean(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('regulation_id', sa.Integer(), nullable=False),
    sa.Column('department_1_id', sa.Integer(), nullable=True),
    sa.Column('department_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_1_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_2_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_id'), 'divisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_divisions_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
